{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teya.pos",
    "module": "unified-sdk-core",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-logger",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-auth-main",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-uicontroller",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-design-system",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result-coroutines",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata.jar",
          "url": "unified-sdk-core-0.0.1-alpha02.jar",
          "size": 45594,
          "sha512": "2936ee5f746593ac2dd9255b7fa00ad0c59cf308bbdc745779ba7391a698dbc03d213b2ccf64aa67478fc560ac7cc26edec4b1bb92e46017e44e133137af5c9f",
          "sha256": "9c5fee16276132013e98328d7415d482c5139ed7ef21ae4976297a1e77c85759",
          "sha1": "c33bb57c9708e821ae831981e82dc12a769bfba6",
          "md5": "b00fd6dacbf3d20c190d2292aae23bbc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-kotlin-sources.jar",
          "url": "unified-sdk-core-0.0.1-alpha02-sources.jar",
          "size": 52957,
          "sha512": "ec038ff55a1ee9dc37c4909e9f09c18135372384749ef905e64678d8e561f2377b9cb5c511f0fc83a57fe00af6b3602d26e093027f5233a9aa92e30977eabcd2",
          "sha256": "c61e5eea6a8185b0d9428ee6e7ebc37beee6f4a455c0c196360a8757cfc221c1",
          "sha1": "c7dbefcc7ac020ddb63281fd5b99a3665e59374d",
          "md5": "4fd5ce82bfbd8411bfe996971a5d2c0e"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-core-android/0.0.1-alpha02/unified-sdk-core-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-core-android/0.0.1-alpha02/unified-sdk-core-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-core-android/0.0.1-alpha02/unified-sdk-core-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosarm64/0.0.1-alpha02/unified-sdk-core-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosarm64/0.0.1-alpha02/unified-sdk-core-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosarm64/0.0.1-alpha02/unified-sdk-core-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosarm64/0.0.1-alpha02/unified-sdk-core-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iossimulatorarm64/0.0.1-alpha02/unified-sdk-core-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iossimulatorarm64/0.0.1-alpha02/unified-sdk-core-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iossimulatorarm64/0.0.1-alpha02/unified-sdk-core-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iossimulatorarm64/0.0.1-alpha02/unified-sdk-core-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosx64/0.0.1-alpha02/unified-sdk-core-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosx64/0.0.1-alpha02/unified-sdk-core-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosx64/0.0.1-alpha02/unified-sdk-core-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-core-iosx64/0.0.1-alpha02/unified-sdk-core-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-core-jvm/0.0.1-alpha02/unified-sdk-core-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-core-jvm/0.0.1-alpha02/unified-sdk-core-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-core-jvm/0.0.1-alpha02/unified-sdk-core-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-core-jvm",
        "version": "0.0.1-alpha02"
      }
    }
  ]
}
