name: teya_pos_sdk
description: Flutter plugin for Teya PosLink SDK (Android only)
version: 1.0.5
homepage: https://github.com/khizar1556/teya_pos_sdk
repository: https://github.com/khizar1556/teya_pos_sdk
issue_tracker: https://github.com/khizar1556/teya_pos_sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.khizar1556.teya_pos_sdk
        pluginClass: TeyaPoslinkSdkPlugin
      ios:
        pluginClass: TeyaPoslinkSdkPlugin
