{
  "formatVersion": "1.1",
  "component": {
    "url": "../../teya-auth-core/0.0.1-alpha02/teya-auth-core-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "teya-auth-core",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "teya-auth-core-jvm-0.0.1-alpha02.jar",
          "size": 171572,
          "sha512": "03f45ef87734dfa12d062b42d2f6a4d5ec15b05000d91e3272771dc7842daab775612d02c9335457badcb09ca85bc1fb98aa12427d1d484fdae43c67b1e0f10f",
          "sha256": "1bcfc21c72323471f9bff114d158fcb80e642c30ea1c411157f1570f10dd72d8",
          "sha1": "084d2d304045d99f2d972fc725faac55d912a55c",
          "md5": "2ad761067d74885fdafd4dd9fb966531"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result-coroutines",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "teya-auth-core-jvm-0.0.1-alpha02.jar",
          "size": 171572,
          "sha512": "03f45ef87734dfa12d062b42d2f6a4d5ec15b05000d91e3272771dc7842daab775612d02c9335457badcb09ca85bc1fb98aa12427d1d484fdae43c67b1e0f10f",
          "sha256": "1bcfc21c72323471f9bff114d158fcb80e642c30ea1c411157f1570f10dd72d8",
          "sha1": "084d2d304045d99f2d972fc725faac55d912a55c",
          "md5": "2ad761067d74885fdafd4dd9fb966531"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "teya-auth-core-jvm-0.0.1-alpha02-sources.jar",
          "size": 17842,
          "sha512": "77694df99922eda458a7308f3c7876d21d1b67e9da4be69f1c19df59db2c1b367a21fc4bf1761db348bdcc68cd85f8e2d07c0e017ff5836a1c3c2fc2bd3bdf9e",
          "sha256": "4b337ef8d05c93579202b75be99a92330b76168a0b1a601f4e8aafb056c7d370",
          "sha1": "6bb33f387b7604a250375ac93e237c7d23249f66",
          "md5": "abfe10aa19d0377eea97ef53153a9001"
        }
      ]
    }
  ]
}
