{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teya.pos",
    "module": "teya-auth-commons",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-logger",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "commons-metadata.jar",
          "url": "teya-auth-commons-0.0.1-alpha02.jar",
          "size": 4446,
          "sha512": "80a083176a630bef0f628f5bc5a15b12c8a24b35822481f880a40b597ace7eed68a4a201ac74f974c650dec780314f9e0c4294dd85014dbbbf147e66cbe84a8c",
          "sha256": "8433834742b3496de8265fc0d3b4fccfab9d1bdf6da0421ba136790ce7ad36c3",
          "sha1": "fa571b55f273f1f5ae7f0b3cc8f3501f9fd5e19f",
          "md5": "ec2286cbcedd772d72daa2865b75d88d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "commons-kotlin-sources.jar",
          "url": "teya-auth-commons-0.0.1-alpha02-sources.jar",
          "size": 2551,
          "sha512": "4b822f018ae7834cc3c81c92d8e517401ef13eb6ae35c2a0a89b76a3ae0fb753c8db93747432a5fc1d6fe8b4de60b0f7d99a6db072d9bff953aa60baa7164cfa",
          "sha256": "d9a4c5ac0d83e30a94785cce6cc6b22055bd69c83410ddc431da3bb1b0095cf3",
          "sha1": "c8b9211878245fe375de9dc3254d87000c740020",
          "md5": "6188a6cde9ed2341a10da78bdf303e94"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iosarm64/0.0.1-alpha02/teya-auth-commons-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iosarm64/0.0.1-alpha02/teya-auth-commons-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iosarm64/0.0.1-alpha02/teya-auth-commons-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iossimulatorarm64/0.0.1-alpha02/teya-auth-commons-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iossimulatorarm64/0.0.1-alpha02/teya-auth-commons-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iossimulatorarm64/0.0.1-alpha02/teya-auth-commons-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iosx64/0.0.1-alpha02/teya-auth-commons-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iosx64/0.0.1-alpha02/teya-auth-commons-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-commons-iosx64/0.0.1-alpha02/teya-auth-commons-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-commons-jvm/0.0.1-alpha02/teya-auth-commons-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-commons-jvm/0.0.1-alpha02/teya-auth-commons-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-commons-jvm/0.0.1-alpha02/teya-auth-commons-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-commons-jvm",
        "version": "0.0.1-alpha02"
      }
    }
  ]
}
