{
  "formatVersion": "1.1",
  "component": {
    "url": "../../unified-sdk-core/0.0.1-alpha02/unified-sdk-core-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "unified-sdk-core",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-logger",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "unified-sdk-core-android-0.0.1-alpha02.aar",
          "size": 2556697,
          "sha512": "afd7d0ffc8fbe41d1ec59b5c8cd342a599faf0f53f4097ad7ef1c46b31dac619dc495442ba1f61bc4b19e57518247443fdf165fb9d0a108f1d00a263378f037f",
          "sha256": "b11bee69d507f2d00040a941a71002b5e7753da63f86dd577dbb1c5c95133551",
          "sha1": "6b70d37810347b4cbb7adffaf6a99b7a14e4af20",
          "md5": "dbcb956789c1ae7ac02b12201a3f5dfe"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-logger",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "android-static-app-provider",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-auth-main",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-uicontroller",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-design-system",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result-coroutines",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "unified-sdk-core-android-0.0.1-alpha02.aar",
          "size": 2556697,
          "sha512": "afd7d0ffc8fbe41d1ec59b5c8cd342a599faf0f53f4097ad7ef1c46b31dac619dc495442ba1f61bc4b19e57518247443fdf165fb9d0a108f1d00a263378f037f",
          "sha256": "b11bee69d507f2d00040a941a71002b5e7753da63f86dd577dbb1c5c95133551",
          "sha1": "6b70d37810347b4cbb7adffaf6a99b7a14e4af20",
          "md5": "dbcb956789c1ae7ac02b12201a3f5dfe"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-android-sources.jar",
          "url": "unified-sdk-core-android-0.0.1-alpha02-sources.jar",
          "size": 55261,
          "sha512": "34fb3e392bfa594b8a3045431afb3a876f359543f41643e474d86ed434b8f76dc7ed179478a8a3b8deea5892a9fa6220b25ea8299ed1c80ec3173d221b9177f3",
          "sha256": "610d3c55df5c3cf714c4e62e8d1ac12c8713d4af53aaef9ee0fc6b440a285df5",
          "sha1": "d14702df329211b81e1a80544cd4fa5fac330a0a",
          "md5": "4c7bb63023428a91c1d2c2c127f58cc7"
        }
      ]
    }
  ]
}
