{
  "formatVersion": "1.1",
  "component": {
    "url": "../../teya-auth-core/0.0.1-alpha02/teya-auth-core-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "teya-auth-core",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "teya-auth-core-android-0.0.1-alpha02.aar",
          "size": 161231,
          "sha512": "e48163ad13db0770c03c48438c92b40da545cac8755b12bd9e765d4289fb57af3f26e55cdd9de1a4a8a52b2983cc45661cba4f64bee54f61eabba0b701b9abb0",
          "sha256": "29e4aad40d88e65eee9a1e8d4653fe5742af14ceb84e2214321d5e4757311092",
          "sha1": "8b3d9a488ea7009f17956d0645d88c9f7eaf0320",
          "md5": "a60052d76b57ebc64354e74e5495098a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result-coroutines",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "teya-auth-core-android-0.0.1-alpha02.aar",
          "size": 161231,
          "sha512": "e48163ad13db0770c03c48438c92b40da545cac8755b12bd9e765d4289fb57af3f26e55cdd9de1a4a8a52b2983cc45661cba4f64bee54f61eabba0b701b9abb0",
          "sha256": "29e4aad40d88e65eee9a1e8d4653fe5742af14ceb84e2214321d5e4757311092",
          "sha1": "8b3d9a488ea7009f17956d0645d88c9f7eaf0320",
          "md5": "a60052d76b57ebc64354e74e5495098a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-android-sources.jar",
          "url": "teya-auth-core-android-0.0.1-alpha02-sources.jar",
          "size": 19045,
          "sha512": "cfd0ce7156d3b94a68822b39cf016e08f7feae6d110406f4e7a998ca55a4e94825dae4ab80af112cd03504f8a8c215a3e508518146b22fb0cdd67fe0f5ba8b7c",
          "sha256": "e3f1afa5b2a46a2e47ebaf8d814c7fd0585f6d8fb96c5bc2b7c2816e9b7d3966",
          "sha1": "7f11dd7a3c60f8d0e7c50d1546aad2ebf72b3c1a",
          "md5": "9de008de6fd60a7e358f45874957c5a3"
        }
      ]
    }
  ]
}
