{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teya.pos",
    "module": "unified-sdk-uicontroller",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-sdk-ui-controller-metadata.jar",
          "url": "unified-sdk-uicontroller-0.0.1-alpha02.jar",
          "size": 2952,
          "sha512": "bc77c10615b932e5465f565d4a7209b4975c15e2bfbbe016b5fcbca96174964725a502c7b65ec73b262a8ff5525913eac108199bd42ff54df2d5db037a106c87",
          "sha256": "24d3cfb1d6166f9c23e7d77ddbfc0c4dc0914f7d0390a2b5f3af295ff120b014",
          "sha1": "68ac24b0b1312cf763ded28e71fb286d146f6b73",
          "md5": "d01d1ea29086aad7f35aa4df0d4b332f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-sdk-ui-controller-kotlin-sources.jar",
          "url": "unified-sdk-uicontroller-0.0.1-alpha02-sources.jar",
          "size": 3104,
          "sha512": "285938280e4a0ab88b88b22aa1ddb119294c3206b742e9a3c8c12c1bf2b639cb2c171af7b6a71074620667fffdb1e8cc93f419d98762154a95e6f1e4e6f804e3",
          "sha256": "0a14992541fee79b4100fb12e2ce1f57b3aa076c540fb141d0b6e32f493868a1",
          "sha1": "76bd2680e9071347c909541486c218280df8a12d",
          "md5": "4e66fadfdd0c1bc38ed270281afd8d12"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-android/0.0.1-alpha02/unified-sdk-uicontroller-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-android/0.0.1-alpha02/unified-sdk-uicontroller-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-android/0.0.1-alpha02/unified-sdk-uicontroller-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosarm64/0.0.1-alpha02/unified-sdk-uicontroller-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosarm64/0.0.1-alpha02/unified-sdk-uicontroller-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosarm64/0.0.1-alpha02/unified-sdk-uicontroller-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosarm64/0.0.1-alpha02/unified-sdk-uicontroller-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iossimulatorarm64/0.0.1-alpha02/unified-sdk-uicontroller-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iossimulatorarm64/0.0.1-alpha02/unified-sdk-uicontroller-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iossimulatorarm64/0.0.1-alpha02/unified-sdk-uicontroller-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iossimulatorarm64/0.0.1-alpha02/unified-sdk-uicontroller-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosx64/0.0.1-alpha02/unified-sdk-uicontroller-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosx64/0.0.1-alpha02/unified-sdk-uicontroller-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosx64/0.0.1-alpha02/unified-sdk-uicontroller-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-iosx64/0.0.1-alpha02/unified-sdk-uicontroller-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-jvm/0.0.1-alpha02/unified-sdk-uicontroller-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-jvm/0.0.1-alpha02/unified-sdk-uicontroller-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-uicontroller-jvm/0.0.1-alpha02/unified-sdk-uicontroller-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-uicontroller-jvm",
        "version": "0.0.1-alpha02"
      }
    }
  ]
}
