{
  "formatVersion": "1.1",
  "component": {
    "url": "../../unified-sdk-core/0.0.1-alpha02/unified-sdk-core-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "unified-sdk-core",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-logger",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "unified-sdk-core-jvm-0.0.1-alpha02.jar",
          "size": 2601921,
          "sha512": "1d5ce47718def46c94e630eba30df25ac50ca395a5cabcba33044bc67cf754e5002c55fc2716856467d419c8c6ae90bb2fe4425c835ef7620d3acbc999ab79bb",
          "sha256": "592f703313efd60eb6ae9427b6fa55382353514f3cbe547d139416356fb9ca5a",
          "sha1": "a0c42dac5bb5d1b599c94fade268da412596235a",
          "md5": "c7c415cb73f4907e41d253969b3c1921"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-logger",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-macos-arm64",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-auth-main",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-uicontroller",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-design-system",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-encoding",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result-coroutines",
          "version": {
            "requires": "1.1.20"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-no-arg",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm.jar",
          "url": "unified-sdk-core-jvm-0.0.1-alpha02.jar",
          "size": 2601921,
          "sha512": "1d5ce47718def46c94e630eba30df25ac50ca395a5cabcba33044bc67cf754e5002c55fc2716856467d419c8c6ae90bb2fe4425c835ef7620d3acbc999ab79bb",
          "sha256": "592f703313efd60eb6ae9427b6fa55382353514f3cbe547d139416356fb9ca5a",
          "sha1": "a0c42dac5bb5d1b599c94fade268da412596235a",
          "md5": "c7c415cb73f4907e41d253969b3c1921"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvm-sources.jar",
          "url": "unified-sdk-core-jvm-0.0.1-alpha02-sources.jar",
          "size": 54441,
          "sha512": "24006ae61a4d13f73b8382739b1500217cfa4e148e2e2c305bd4e84074c9f286d2b5d18810a131798bcaeede56eee7889b8e19a434d0843d516c64bda09845f6",
          "sha256": "5cb34d2bf2eac19f6d6370a31254b2e196449a8ea6d6bdeaf84363df07d968dc",
          "sha1": "a77ad4d51f6195e78fc475f14624d56c469826f4",
          "md5": "1a13baf01aa294d01c00978318de424a"
        }
      ]
    }
  ]
}
