{
  "formatVersion": "1.1",
  "component": {
    "url": "../../teya-auth-main/0.0.1-alpha02/teya-auth-main-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "teya-auth-main",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "main.aar",
          "url": "teya-auth-main-android-0.0.1-alpha02.aar",
          "size": 202135,
          "sha512": "6b215bd447b89e333d8e7aeea6d6cf040f66dffe5a1bf990a7d4ac2287454e71e386b946598f617899323f1ee8cd1834aac5b62126e945887bc72003632d52ec",
          "sha256": "783d89af70b7d9a05b5a479181ff1ae3f6b950711ea4bc1392a759c8a99d26aa",
          "sha1": "1ec22f6900b00eb76344c81e8a6d41475298edcd",
          "md5": "3daf07cc4982c92fde1aac8510b7f9ef"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-uicontroller",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-auth-core",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-design-system",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "main.aar",
          "url": "teya-auth-main-android-0.0.1-alpha02.aar",
          "size": 202135,
          "sha512": "6b215bd447b89e333d8e7aeea6d6cf040f66dffe5a1bf990a7d4ac2287454e71e386b946598f617899323f1ee8cd1834aac5b62126e945887bc72003632d52ec",
          "sha256": "783d89af70b7d9a05b5a479181ff1ae3f6b950711ea4bc1392a759c8a99d26aa",
          "sha1": "1ec22f6900b00eb76344c81e8a6d41475298edcd",
          "md5": "3daf07cc4982c92fde1aac8510b7f9ef"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "main-android-sources.jar",
          "url": "teya-auth-main-android-0.0.1-alpha02-sources.jar",
          "size": 23672,
          "sha512": "08964d1d6ba2e7f390f34502df6f62de4ee4418129a089e674a641c21e54b74167571189923eff3f4df00975bdc6cda4b5795483712a626b12fd959d6d3b88d2",
          "sha256": "836938813bc0fab36f9b0b622a486e6b35285797dd55ac8faf71d6e14d4c0b70",
          "sha1": "9244127dcc421ea67c80340a419011b86fff3f4f",
          "md5": "16e42ba043fbfe7c925edc2d1352d53f"
        }
      ]
    }
  ]
}
