{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teya.pos",
    "module": "android-static-app-provider",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "android-static-app-provider-0.0.1-alpha02.aar",
          "url": "android-static-app-provider-0.0.1-alpha02.aar",
          "size": 3385,
          "sha512": "801b3addfa1e8091b18a73ee12b58c0d6cc0e1dc456b67bb9935be06c25154a2c9a48b8d5c95a67034f27d50a6492e175ac78544c1743c52ce25c35d48b96be1",
          "sha256": "ff1481c321ad68936bf8e6bf19f05d5e1bf465fccc9aae479b460365cf2f67db",
          "sha1": "d543b4a6321339fb5809145af13bb871124040f6",
          "md5": "3320f83a54f90aa454e6d3ca41d5ffd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "android-static-app-provider-0.0.1-alpha02.aar",
          "url": "android-static-app-provider-0.0.1-alpha02.aar",
          "size": 3385,
          "sha512": "801b3addfa1e8091b18a73ee12b58c0d6cc0e1dc456b67bb9935be06c25154a2c9a48b8d5c95a67034f27d50a6492e175ac78544c1743c52ce25c35d48b96be1",
          "sha256": "ff1481c321ad68936bf8e6bf19f05d5e1bf465fccc9aae479b460365cf2f67db",
          "sha1": "d543b4a6321339fb5809145af13bb871124040f6",
          "md5": "3320f83a54f90aa454e6d3ca41d5ffd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-static-app-provider-0.0.1-alpha02-sources.jar",
          "url": "android-static-app-provider-0.0.1-alpha02-sources.jar",
          "size": 1170,
          "sha512": "8f7b817ec97ab05d339a90701c4f69a848ec733611603133ff3f6c140b1eb2a97897ca55672c5ac6229b2c54056b83c0ef13068aacb0475858e95c0e15659cec",
          "sha256": "c900c104674d7d79952c4e775e68b917b29eeb6cdc7231c4f6cbcaa43a739da3",
          "sha1": "db0502ba758e0cb4a6007b85d5a8994fee83bdfe",
          "md5": "6a0fef1d4e5a209d72fa53d6baee6d71"
        }
      ]
    }
  ]
}
