{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teya.pos",
    "module": "unified-sdk-logger",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "commons-logger-metadata.jar",
          "url": "unified-sdk-logger-0.0.1-alpha02.jar",
          "size": 2459,
          "sha512": "bcf39e4da55029f8eaa7f98e8acbaf7e90d3d220f15ac9e5a537730d42150bc2a47aa4e61804f7bfa938a160534ec9711ac66c50502cd944a939824170d57868",
          "sha256": "9e4da4ba07fb0795f98795c7ef6ae0e83f2b2ae481cabe9b53c482d860b008d3",
          "sha1": "7b2d6a54fc876030e3254af20acde56280a99b7d",
          "md5": "ffe296ad9fd4d3809a6709366baae720"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "commons-logger-kotlin-sources.jar",
          "url": "unified-sdk-logger-0.0.1-alpha02-sources.jar",
          "size": 1237,
          "sha512": "974c3be7b9e928787cd780fbf054a05bdc4e96a0961bcefd70570b3aaaeda7737e441b39e755911f28c4ffe1aec3e4f44c74c53ca13bbefecb1f080044e8d4fe",
          "sha256": "a714891e200b6b0eb0c8c587ae3b27b762a662d3db7a37aa593be2c7b7152688",
          "sha1": "c30ce987eb09f2c7b4416829fae5cf46299132b6",
          "md5": "f462790d53a4da07f4a3e577cadb4b87"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iosarm64/0.0.1-alpha02/unified-sdk-logger-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iosarm64/0.0.1-alpha02/unified-sdk-logger-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iosarm64/0.0.1-alpha02/unified-sdk-logger-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iossimulatorarm64/0.0.1-alpha02/unified-sdk-logger-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iossimulatorarm64/0.0.1-alpha02/unified-sdk-logger-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iossimulatorarm64/0.0.1-alpha02/unified-sdk-logger-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iosx64/0.0.1-alpha02/unified-sdk-logger-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iosx64/0.0.1-alpha02/unified-sdk-logger-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-iosx64/0.0.1-alpha02/unified-sdk-logger-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-jvm/0.0.1-alpha02/unified-sdk-logger-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-jvm/0.0.1-alpha02/unified-sdk-logger-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../unified-sdk-logger-jvm/0.0.1-alpha02/unified-sdk-logger-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "unified-sdk-logger-jvm",
        "version": "0.0.1-alpha02"
      }
    }
  ]
}
