{
  "formatVersion": "1.1",
  "component": {
    "url": "../../teya-auth-main/0.0.1-alpha02/teya-auth-main-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "teya-auth-main",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "main-jvm.jar",
          "url": "teya-auth-main-jvm-0.0.1-alpha02.jar",
          "size": 210000,
          "sha512": "d45144ab6326f634bf5e35936d3d9653d1313ecc09462bf8bd63c3ace5a2bca8d1e77fb44b0d218df158bbb28810da4fc07f8248a9724130a977305558bc256f",
          "sha256": "ed17b64f3c016ab1afa36e42e8460e0ca31b8b914749bdf935e15f2f91e7986d",
          "sha1": "49e52bf1aefdf265d98bbd318a008701010eb81f",
          "md5": "fdf55eebc75e956715e296a7d440a996"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-macos-arm64",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-uicontroller",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-auth-core",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-design-system",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "main-jvm.jar",
          "url": "teya-auth-main-jvm-0.0.1-alpha02.jar",
          "size": 210000,
          "sha512": "d45144ab6326f634bf5e35936d3d9653d1313ecc09462bf8bd63c3ace5a2bca8d1e77fb44b0d218df158bbb28810da4fc07f8248a9724130a977305558bc256f",
          "sha256": "ed17b64f3c016ab1afa36e42e8460e0ca31b8b914749bdf935e15f2f91e7986d",
          "sha1": "49e52bf1aefdf265d98bbd318a008701010eb81f",
          "md5": "fdf55eebc75e956715e296a7d440a996"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "main-jvm-sources.jar",
          "url": "teya-auth-main-jvm-0.0.1-alpha02-sources.jar",
          "size": 23266,
          "sha512": "1daabf65e376a8edbc00230580bcb2bbb2edf54693bda381d937753c1fc8d2559e74482175f028ea53319bd39b1e90f67ca4a2083c2f580f3601ee63f0138ff3",
          "sha256": "ccfc30af875e4d6a0916b624448b74a0e0767cdda0836b59ef876ac71c7128e7",
          "sha1": "0eb23b8ec8e7d41a127fa2d593b85c6933171016",
          "md5": "1ddd4451baadc3d9f4c923c3ab1c6043"
        }
      ]
    }
  ]
}
