{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teya.pos",
    "module": "teya-auth-main",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.teya.pos",
          "module": "teya-auth-commons",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "unified-sdk-uicontroller",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-auth-core",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "com.teya.pos",
          "module": "teya-design-system",
          "version": {
            "requires": "0.0.1-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "main-metadata.jar",
          "url": "teya-auth-main-0.0.1-alpha02.jar",
          "size": 13636,
          "sha512": "09d9130e013bc580b0fadf03e451eb0f34f45d1cfb0d60c04522b1844c26a40176ba3583155efa05065318cb472ee5c3d888ef3396eac898b64c5139c2a737e7",
          "sha256": "e25027d6cd9f40fdf8f5ad7a7da616dc052a3941c9bf7b2d8e9bb614e1e670b0",
          "sha1": "cdbd5def1363fbcacfb621fddbfb0817709a95f6",
          "md5": "4de14c401126d06dc8a122a1c01d03d6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "main-kotlin-sources.jar",
          "url": "teya-auth-main-0.0.1-alpha02-sources.jar",
          "size": 21925,
          "sha512": "3df5ef4cdad5fd4c75f9ebe3f3e69f3669df8dd3a1f01162089514d37526ce960416b18ac28ed8dcf0c3e7dd8b264cd6224082159d4e1d809f282ce0594df277",
          "sha256": "f9743c6cd59b0ca9ac606dc6c9596c18eea62d2015f1943131141ae4f3ac4fc3",
          "sha1": "12740bf4799c42e3a93dfacab65d18b2da6b1ced",
          "md5": "265c09f489bf4357730b0a11bee2c61b"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-main-android/0.0.1-alpha02/teya-auth-main-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-main-android/0.0.1-alpha02/teya-auth-main-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-main-android/0.0.1-alpha02/teya-auth-main-android-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-android",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosarm64/0.0.1-alpha02/teya-auth-main-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosarm64/0.0.1-alpha02/teya-auth-main-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosarm64/0.0.1-alpha02/teya-auth-main-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosarm64/0.0.1-alpha02/teya-auth-main-iosarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iossimulatorarm64/0.0.1-alpha02/teya-auth-main-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iossimulatorarm64/0.0.1-alpha02/teya-auth-main-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iossimulatorarm64/0.0.1-alpha02/teya-auth-main-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iossimulatorarm64/0.0.1-alpha02/teya-auth-main-iossimulatorarm64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iossimulatorarm64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosx64/0.0.1-alpha02/teya-auth-main-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosx64/0.0.1-alpha02/teya-auth-main-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosx64/0.0.1-alpha02/teya-auth-main-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../teya-auth-main-iosx64/0.0.1-alpha02/teya-auth-main-iosx64-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-iosx64",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-main-jvm/0.0.1-alpha02/teya-auth-main-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-main-jvm/0.0.1-alpha02/teya-auth-main-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-jvm",
        "version": "0.0.1-alpha02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../teya-auth-main-jvm/0.0.1-alpha02/teya-auth-main-jvm-0.0.1-alpha02.module",
        "group": "com.teya.pos",
        "module": "teya-auth-main-jvm",
        "version": "0.0.1-alpha02"
      }
    }
  ]
}
