{
  "formatVersion": "1.1",
  "component": {
    "url": "../../unified-sdk-logger/0.0.1-alpha02/unified-sdk-logger-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "unified-sdk-logger",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "commons-logger-jvm.jar",
          "url": "unified-sdk-logger-jvm-0.0.1-alpha02.jar",
          "size": 2388,
          "sha512": "2b5b4f342c09f2d07dcc70b3385e536d3f5431735100de5bd13f1e4bbb286571795875845584b4955b323b06e9af3bd8542ff1ce480212b87edc60a06696314c",
          "sha256": "cf996132a65c6de5e500e44bd79760f46ce70b7fa9ad6df43e180bc939e37923",
          "sha1": "ccd67452a69610cc0a46b89376f18db21a85c78c",
          "md5": "5465aa19c36fda48290335606ae544d1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "commons-logger-jvm.jar",
          "url": "unified-sdk-logger-jvm-0.0.1-alpha02.jar",
          "size": 2388,
          "sha512": "2b5b4f342c09f2d07dcc70b3385e536d3f5431735100de5bd13f1e4bbb286571795875845584b4955b323b06e9af3bd8542ff1ce480212b87edc60a06696314c",
          "sha256": "cf996132a65c6de5e500e44bd79760f46ce70b7fa9ad6df43e180bc939e37923",
          "sha1": "ccd67452a69610cc0a46b89376f18db21a85c78c",
          "md5": "5465aa19c36fda48290335606ae544d1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "commons-logger-jvm-sources.jar",
          "url": "unified-sdk-logger-jvm-0.0.1-alpha02-sources.jar",
          "size": 1237,
          "sha512": "974c3be7b9e928787cd780fbf054a05bdc4e96a0961bcefd70570b3aaaeda7737e441b39e755911f28c4ffe1aec3e4f44c74c53ca13bbefecb1f080044e8d4fe",
          "sha256": "a714891e200b6b0eb0c8c587ae3b27b762a662d3db7a37aa593be2c7b7152688",
          "sha1": "c30ce987eb09f2c7b4416829fae5cf46299132b6",
          "md5": "f462790d53a4da07f4a3e577cadb4b87"
        }
      ]
    }
  ]
}
