{
  "formatVersion": "1.1",
  "component": {
    "url": "../../teya-design-system/0.0.1-alpha02/teya-design-system-0.0.1-alpha02.module",
    "group": "com.teya.pos",
    "module": "teya-design-system",
    "version": "0.0.1-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "teya-design-system-jvm.jar",
          "url": "teya-design-system-jvm-0.0.1-alpha02.jar",
          "size": 487626,
          "sha512": "344b80e7d1f95b1f4d482f0942ca82562205bfe99b24ef9fd65d980b7d819b23b296242f10cff49100685e7e3a56de282ce9d086f12c1e5814e8abebacf15db4",
          "sha256": "1ad83466b79c68c7139f8ccabd08d366629ef18128b7bb2205b46be15c2df827",
          "sha1": "80a4c4c41e57f49b55ed94e6b7828ce1ae20535a",
          "md5": "db0563e47a9d621c577d920e52e2f629"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-macos-arm64",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "teya-design-system-jvm.jar",
          "url": "teya-design-system-jvm-0.0.1-alpha02.jar",
          "size": 487626,
          "sha512": "344b80e7d1f95b1f4d482f0942ca82562205bfe99b24ef9fd65d980b7d819b23b296242f10cff49100685e7e3a56de282ce9d086f12c1e5814e8abebacf15db4",
          "sha256": "1ad83466b79c68c7139f8ccabd08d366629ef18128b7bb2205b46be15c2df827",
          "sha1": "80a4c4c41e57f49b55ed94e6b7828ce1ae20535a",
          "md5": "db0563e47a9d621c577d920e52e2f629"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "teya-design-system-jvm-sources.jar",
          "url": "teya-design-system-jvm-0.0.1-alpha02-sources.jar",
          "size": 23242,
          "sha512": "fbecff2655e41af9b4ec354415ffb40b005a27e38979a1db981a93d4cf81b7ece94fb4b47e853e9e80174957ea729a88c1334c99f0562de6940bb56c212a3929",
          "sha256": "8c646d7a85afad153f43915cf1991eaf61739727354e58258281d83942d9112b",
          "sha1": "1c51b59a61836a07e913579b65d23b94cbd7830e",
          "md5": "87b86b910db4170cf695aa736be8dd4c"
        }
      ]
    }
  ]
}
